setono_sylius_meilisearch_admin_indexable_attribute:
    resource: |
        section: admin
        alias: setono_sylius_meilisearch.indexable_attribute
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_meilisearch_admin_indexable_attribute
        vars:
            all:
                header: setono_sylius_meilisearch.ui.indexable_attribute_header
                subheader: setono_sylius_meilisearch.ui.indexable_attribute_subheader
                templates:
                    form: "@SetonoSyliusMeilisearchPlugin/admin/indexable_subject/_form.html.twig"
    type: sylius.resource

setono_sylius_meilisearch_admin_indexable_option:
    resource: |
        section: admin
        alias: setono_sylius_meilisearch.indexable_option
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_meilisearch_admin_indexable_option
        vars:
            all:
                header: setono_sylius_meilisearch.ui.indexable_option_header
                subheader: setono_sylius_meilisearch.ui.indexable_option_subheader
                templates:
                    form: "@SetonoSyliusMeilisearchPlugin/admin/indexable_subject/_form.html.twig"
    type: sylius.resource

setono_sylius_meilisearch_admin_synonym:
    resource: |
        section: admin
        alias: setono_sylius_meilisearch.synonym
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_meilisearch_admin_synonym
        vars:
            all:
                header: setono_sylius_meilisearch.ui.synonym_header
                subheader: setono_sylius_meilisearch.ui.synonym_subheader
                templates:
                    form: "@SetonoSyliusMeilisearchPlugin/admin/synonym/_form.html.twig"
    type: sylius.resource
